### ISSUE TITLE
Mod Manager 6.2 Checklist

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#134]
List of things hopefully planned for 6.2

**User features**
- [x] Diagnostics: Check for incompatible DLC setup
- [x] Diagnostic: Throw errors when seeing multiple same ASI
- [x] Updater Service: download all - Needs further testing!
- [x] Mod archive importing: Disable package compression if updatecode is specified
- [x] Mod Installer: Choose install target
- [x] Mod Installer: Support choosing compression
- [x] Have a way to show all of what will be installed to user. E.g. So they can see what files are going to be installed into basegame. So when they say 'any mod that touches... X' they can possibly tell. However, this will only be estimate as actual installation options are not calculated until installation commences and the installation queues are built
- [x] Updater Service: Check if existing file is in manifest before looking at decompressed data
- [x] Update Installation Information panel's ALOT section for new V4 possible configs

**Developer features**
- [x] Check if mod is in TPMI when deploying and advertise telemetry submission
- [x] Moddesc Editor
- [x] Moddesc 6.2: Support images in alternates
- [x] Support banner images for mods
- [x] Deployment: Choose validation target
- [x] _metacmm.txt: Store incompatible DLC
- [x] Deployment: Check for bad properties
- [x] Deployment: Support multiple mods (this will require significant overhaul of deployment and way of selecting multiple mods)

**Internal changes**
- [x] Rebase file handling backend onto ME3ExplorerCore
- [x] Switch to .NET 5
      - The app still ships on .NET Core 3.1 because AppCenter does not appear to be compatible with .NET 5 Single-file executables, which means I have no crash telemetry, which significantly crippled ability to fix bugs. The app is built and tested on .NET 5 but is built against .NET Core 3.1
- [x] _metacmm.txt: Options chosen at installation time
- [x] Remove GUI Compatibility Pack Generator + associated code
- [x] Updater Service: Disallow compressed package upload
- [x] Classic updater: Support rename operations by indexing all references instead of server references

**Localization**
 - [x] Localize to INT

**Todo**
 - [x] Steam game lookup before first run - Needs target switching and game launch testing
 - [x] Update moddesc documentation

**Something that will be done someday, maybe**
- Make new mod format for porting assets into existing file... ugh...
