### ISSUE TITLE
Mod Manager 6.2.2 checklist

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#200]
List of items to be released for 6.2.1.

- [x] Change over other target selectors to the new TargetSelector class
- [x] Fix 'No mods in the mod library!' showing if all three filter options are set to off, since this is a wrong message. Maybe just change the title text?
- [x] Fix 'glitchy' behavior in the Custom DLC mod importer, due to dialog changing size while mouse is still down and it causing a re-selection
- [x] Remove ME3Tweaks dependency by including 7z native dll in download. The original reason it was not included was to reduce update size, which is not a concern using the patch system which will not include the dll data once it's downloaded once

**Fixed in 6.2 re-releases**
- [x] Update IAmViolin's name to Arch-Violin
- [x] Merge in ALOT Installer Log Collector improvements
- [x] Fix crash in Mod.Equals(). (Due to RCW mods not having a ModPath set)

**Moved to 6.2.2**
- [ ] Enable LaunchThroughOrigin UI option
- [ ] Fix crash due to accessing ME3ExplorerCore's instance when it's null. Appears to only be affecting first boot + add target ? Is CoreLib not initializing on first boot?
- [x] Disable modified basegame files/Modified DLC archives from showing anything if game is texture modded
- [x] Add 'DLC' tab to Installation Information and list official DLC
- [x] Show installed options in Installation Information (maybe through hyperlink? Expander?)

**Delayed until some other point in time**
 - Test .NET 5 with new appcenter workaround https://github.com/microsoft/appcenter-sdk-dotnet/issues/1483
    - Microsoft has **still** not fixed this issue so we are stuck on .NET Core 3.1 still.
