### ISSUE TITLE
Build 104 todo list

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#27]
This is the todo list for ME3Tweaks Mod Manager 6.0 Preview 5, Build 104.

This build is currently soak testing and will be re-issued as bugs are reported before a wider release.

**Features that are yet to be implemented**
 - None

**Mods planned for supporting**
 - [x] PEOM 1.5.2
 - [x] Other ME2 specific items
 - Convert finalizer realistic gravity mixins to non-finalizer by changing RealTimeSeconds name entry to DefaultGravityZ and swapping the float value (this can be done at any time since this is serverside)

**Bugs needing fixed**
 - [x] TPMI Submission - ALOV for ME3 is missing Optionals folder. - Fixed by some previous commit in 104, not sure which
 - [x] Re-create realistic gravity mixin for MPCer3 as it breaks file. Issue is also present in ME3CMM, seems to be bad jsf file in mixin package on the server
 - [x] Re-create realistic gravity mixin for MPCer as it doesn't seem to work in M3 or ME3CMM. Seems to be bad jsf
 - [x] Handle corrupt archive files
   - May need to be revisited depending on when the error occurs. This should catch any issues when initially parsing the files, but we may have issues down the road when data is being extracted itself.

**Features - In need of validation**
 - [x] Batch Installer
 - [x] ME3Tweaks ModMaker
 - [x] Updater Service Uploader for devs
 - [x] Setup wizard
 - [x] Import a mod from DLC directory
 - [x] Filter in target info restore UI
 - [x] Each game - tool to set what keys are used for the console
 - [x] AutoTOC after files are restored (ME3) (only for restore all basegame files)
 - [x] Mod updater system: ME3Tweaks ModMaker
 - [x] Multilists for Basegame and Official DLC headers
 - [x] Mod updater system: NexusMods whitelist
 - [x] Backup nag system
 - [x] Migrate settings from app data to programdata
 - [x] Workaround for breaking change for TPMI ME3 mod imports that will fail to pass validation due to missing game attribute in builds 103 and below
 - [x] Mixins (front end for new mods)
 - [x] Escape pressing in usercontrols
 - [x] Tooltips
 - [x] Target Info: searchable basegame files

**Features - Validated**
 - [x] Mod-Parsing: minsupportedbuild to prevent loading mods on same-version spec builds while spec is in development
 - [x] Mixins (back end)
 - [x] Multilists for CustomDLC - Tested on Priority Earth Overhaul Mod 1.5.2

**Localizations**
 - [x] Localization pass: English
 - [x] Localizer tool - needs validated
   - ~~[ ] Support forks~~ No longer necessary
   - [x] Support local file saving and loading
 - ~~[ ] Localize French, Polish, Spanish~~ These languages are no longer supported
 - [x] Update localizations from 103 -> 104: Russian, German

**Documentation**
 - [x] Documentation for 103 (missing)
 - [x] Documentation for 104

**Deployment**
 - [x] Soak Test - In progress
 - [x] Full Release

**New mods supported**
These mods will become available for importing and install once deployment goes to Full Release
 - [x] ME2 No Mini Games - pending validation and server moddesc
 - [x] ME2 Vignette Remover - pending validation and server moddesc

**Moved to 105**
 - Three Way Merge (backend is in 104)
 - Beta mode
 - Diagnostics in log
 - Mixins - Merge into existing mods
 - Migrate from ME3CMM automated procedure
 - Drag/Drop coalesced compiler
 - Drag/Drop TLK Compiler/ME3Exp TLK Editor Launcher (ME3Exp will have to be updated or TLK Editor ported)
 - Directly apply mixins

**Comment by HarHarLinks** [comment]
Backup nag system seems to work for me, at least it keeps nagging about ME3 which I don't have backed up atm.

**Comment by Mgamerz** [comment]
# Changelog for ME3Tweaks Mod Manager 6.0 Preview 4 (Build 104)
This build adds the most of the remaining features from Mass Effect 3 Mod Manager as well as adding several new features.

# New features
 - Now includes support for ME3Tweaks ModMaker, an online mod creation tool for ME3
 - Now includes support for Mixins, premade patches for Mass Effect 3
 - Can now toggle custom DLC in Target Info
 - Can now use Batch Mod Installer
 - Can now import mods from game DLC directory
 - Can now change what keys bring up the console with the Console Keybinder in the tools menu
 - Developer mode feature: Backup file fetcher - quickly find and fetch files from backups, including in SFARs
 - Supports new advanced modding features that will enable mods such as PEOM and No Minigames to work with Mod Manager

# Changed features
 - Polish, French, and Spanish localizations have been removed from the interface as I do not have any localizers available for these languages.
 - Added a backup nag system to encourage users to create backups
 - Whitelisted mods can check for updates against NexusMods if they follow a list of rules
 - Running Mass Effect Modder will now run Mem Qt instead of Mem C#
 - When injecting files into SFARs, if the new data size is same as old data size or less, it will replace data in-place rather than appending. This will prevent SFAR from growing constantly in some instances
 - Updated the ME2, ME3 MD5 databases to include .bin and .ini files
 - Better logging and telemetry data for finding bugs
 - Require backups to have a vanilla marker file - if file is missing, backup will be validated and marker will be placed. If backup cannot be validated (such as from alot installer) it will be considered invalid and ignored. Mod Manager will not work with modified backups due to features that depend on backups
 - UI improvements for filesize strings


# Bugfixes
 - Prevent crash if user tries to install an ASI mod to a game when there is not target selected for that game
 - Prevent crash if ME2 Coalesced.ini file is malformed
 - Prevent crash if ME1 BioInput.ini file is marked read-only
 - Prevent crash if ME1 game config utility is set to run as admin and the tool is launched from M3
 - Prevent startup crash if the system has no antivirus listed in Windows Security Center
 - Improve log upload speed and reliability
 - Improve crash handling for settings/target list files when the files are locked for reading
 - Fix deployment storing incorrect filepaths in 7zip with two backslashes
 - Fix a bug where some RCW mods may appear as invalid
 - Ignore PCConsoleTOC.bin files when doing a consistency check to avoid bug in the autotoc.asi file
 - Fix some memory leaks in Installation Information panel
 - Prevent crash if invalid settings.ini is attempted to be read
 - Move application data to %ProgramData% to fix crash when the appdata filepath has unicode characters in it such as Hebrew usernames
 -

**Comment by HuntersRun1** [comment]
Not sure if this is the right place, but import mod from dlc works for me.  A suggestion - either grey out or remove the mods you already imported. Otherwise the mods imported and applied.
