### ISSUE TITLE
Build 105 checklist

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#73]
This is the task list for ME3Tweaks Mod Manager, Build 105.

# New features
 - [x] File-level rules for alternates - needs validation
 - [x] Importing blacklist
 - [x] Mod check for update on import if mod is updatable - needs validated 
 - [x] ME3CMM migration flow
 - [x] Support EGM settings - needs validation
 - [x] #77 Moddesc altfiles: COND_ALWAYS
 - [x] #81 Updater Service delta for upload - needs validation
 - Drag/drop tools for devs
   - [x] Coalesced decompiler
   - [x] Coalesced compiler
   - [x] TLK decompiler
   - [x] TLK compiler
 - [x] Drag/drop Modmaker sideload for xml files
 - [x] altdlc: COND_SPECIFIC_DLC_SETUP
 - [x] Conflict Detector UI for devs - needs validation
 - [x] Basegame File Identification Service (diag only for now)
 - [x] Official DLC Toggler - needs validation, especially for ME2, ME1
 - [x] New option: Auto LODs

# Changed features
 - [x] Significantly improved log and diagnostics, on par with ALOT Installer - needs validation
 - [x] Prevent RCW mod deployment - needs validation (with other mod deployments too)
 - [x] #80 Restoring game should update the LODs if it's an active target - needs validation
 - [x] Updated to May .NET Core to resolve windows wiping out temp directory

# Other things
 - Localizations
    - [ ] French
    - [x] Polish
    - [x] German
    - [x] Russian
 - [x] Beta test
 - [x] Documentation
 - [x] Soak test (in progress)
 - [x] Full deployment

# Moved to 106
 - Direct Mixin installation, using three way merge
   - This will require further work than initially anticipated for multiple changes to the same export. It is partially implemented, but when merges are rejected, the UI is not informed
 - Three Way Merge - will take additional implementation work to support merging changes to same-exports and when to allow or deny these changes
 - RCW mods - support in deploy? maybe a mod will bundle a basegame coalesced change...? seems like a bad idea
 - RCW mods - support with other tasks, maybe a mod will bundle a basegame coalesced change...? seems like a bad idea

**Comment by Mgamerz** [comment]
# Changelog for ME3Tweaks Mod Manager 6.0 (Build 105)
This build brings ME3Tweaks Mod Manager out of the preview stage, and will soon replace Mass Effect 3 Mod Manager (ME3CMM) once this build has stabilized.

This build adds many new developer features for more advanced mods such as conditional installs based on existing files, rules for very specific DLC setups, and always enforced options for better conveyance of information to users.

# New features
 - Now contains the ME3CMM migration setup that will migrate ME3CMM mods, external tools, and settings into M3
 - Right click a mod for Mod Utils
 - Added Basegame File Identification Service. If telemetry is turned on, information about basegame files that are installed will be sent to ME3Tweaks. I am using this information to build a database of basegame files/hashes that can be used to identify basegame files. Currently the only place this will be used is diagnostics, but eventually it will be in Installation Information once I build up a bigger database
 - Mixin Direct installation
   - This is in preview, and is not 100% functional due to the complexity of three way merge. This functionality will be enhanced in the future
 - Complete overhaul of the logging/diagnostics functionality to be actually useful. It now produces logs even more detailed than ALOT Installer with more nifty features
 - Active game targets will now show the source of their installation source as an icon: Origin, Steam, DVD
 - **For developers**
    - Deploying ME1 mods now checks for broken textures
    - Drag and drop support for your favorite files:
        - Coalesced.bin/xml
        - TLK binary/xml (tankmaster manifest, tankmaster data, me3explorer data xmls)
    - EGM Settings is now an external tool to M3
    - New Alternate Condition: COND_ALWAYS. This always is checked, and can be combined with OP_NOTHING to convey things to users, like something is always being installed. Useful in a few niche scenarios
    - New AlternateDLC Condition: COND_SPECIFIC_SIZED_FILES. Allows you to write a condition that looks for specifically sized files. Useful for mods that have configuration options that you need to switch on, for example ALOV's upscale depending on specific options for other mods.
    - Add Conflict Detector, available only in dev mode
    - Add Official DLC Toggler (ME1 and ME2 will load DLC from all folders in their DLC dir, so this won't disable them officially, only for purposes of testing with Mod Manager)
    - Open Moddesc.ini directly from the Developer Options menu in Mod Utils

# Changed features
 - Deployment window UI has been updated to better reflect that it's doing something if an error occurs and changes the icon from the spinner to an X
 - **Target Info** has been changed to **Manage Installation**.
 - Backup File Fetcher now fetches TLK files for ME2 and ME3
 - Updater Service upload will now show the delta to be applied to the server before you commit it
 - You can no longer attempt to deploy RCW based mods. It didn't work anyways, this will now actively block it
 - If you use ALOT Installer and have a custom texture library set, if you drag/drop the main archive it will move it to the library area. People seem to think Mod Manager is ALOT Installer for some reason, I guess users don't read the directions

# Bugfixes
 - Mod loader is much faster now due to not sorting on every addition. This will make the load look a bit wonkier but will be much, much faster
 - Backups would use string_Basegame and string_Movies instead of their translated equivalents, fix Updater Service string spacing (thanks @Kinkojiro)
 - Multiple try/catches have been added to the mod installer that should prevent app crash in the event something goes wrong, and will notify the user. This is due to things like CRC32 errors for example, which indicate disk failure/archive corruption
 - Mass Effect Ini Modder: Fix crash when doing Reset All due to changes from .NET Framework to .NET Core
 - Fix issue in mod updater that prevented NexusMods Update Notifications from being deployed to production in 104
 - Fix memory leak in Installation Information window that could lead to huge loss of performance
 - Updated checks for if game is running to poll no more than once every 5 seconds (could lead to huge performance loss)
 - Fix bug in Directory.GetFiles() implementation for archives. This fixes a bug that would occur when installing a mod such as Same Gender Romances for ME1 from archive when picking certain options that would make it think it didn't install everything when it actually installed too many things
 - Fix bug that would cause ME3Tweaks ModMaker mods to fail to load after compile because newlines weren't escaped in the mod description which resulted in invalid moddesc.ini files
